contents:
  packages:

accounts:
  groups:
    - groupname: rstudio-server
      gid: 65532
  users:
    - username: rstudio-server
      uid: 65532
      gid: 65532
  run-as: 65532

paths:
  - path: /var/run
    type: directory
    permissions: 0o777
    gid: 65532
    recursive: true
  - path: /var/lib/rstudio-server
    type: directory
    permissions: 0o777
    gid: 65532
    recursive: true
  - path: /var/log/rstudio/rstudio-server
    type: directory
    permissions: 0o777
    gid: 65532
    recursive: true

entrypoint:
  command: /usr/bin/rserver
